[package]
name = "haws"
version = "0.1.1"
authors = ["maxim"]
edition = "2021"
description="a crate to build a web server similar to express js"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
